### ISSUE TITLE
unsupported rule type RULE-SET

### ISSUE THREAD

**Issue by flystaros** [LondonX/clash_flt2#11]
config validate failed: rules[0] [RULE-SET,LocalAreaNetwork,🎯 全球直连] error: unsupported rule type RULE-SET

**Comment by LondonX** [comment]
Does the same yaml works on any other build of clash?

This repo is only a plugin to make clash core works with Flutter, so most features should be aligned with clash core.

**Comment by jzau** [comment]
`RULE-SET` is only available in the Premium clash core edition.

**Comment by LondonX** [comment]
So, I'm closing this as not planned.
