### ISSUE TITLE
How to build libclash.so & hev-socks5-tunnel.so

### ISSUE THREAD

**Issue by hiFrankYoung** [LondonX/clash_flt2#6]
Hello, Could u give some guides of building these .so files

**Comment by hiFrankYoung** [comment]
I find libclash build method.

And how to build libhev-socks5-tunnel.so?

**Comment by LondonX** [comment]
Sure
for building libclash
```shell
cd fclash
./build_libclash
```
and for build libhev-socks5-tunnel, you may clone this repo [](https://github.com/heiher/hev-socks5-tunnel), and run `ndk-build` in `hev-socks5-tunnel` dir.

Make sure you have golang and NDK environment installed.
