### ISSUE TITLE
找不到文件

### ISSUE THREAD

**Issue by Betterforme** [LondonX/clash_flt2#8]
lib/home_view.dart:7:8: Error: Error when reading 'lib/sensitive_data.dart': 系统找不到指定的文件�?

**Comment by Betterforme** [comment]
lib/home_view.dart:7:8: Error: Error when reading 'lib/sensitive_data.dart': 系统找不到指定的文件�?

import 'package:clash_flt2_example/sensitive_data.dart';
       ^
lib/home_view.dart:33:41: Error: The getter 'yamlUrl' isn't defined for the class '_HomeViewState'.
 - '_HomeViewState' is from 'package:clash_flt2_example/home_view.dart' ('lib/home_view.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'yamlUrl'.
    final resp = await GetConnect().get(yamlUrl);

**Comment by LondonX** [comment]
这里面是Clash配置文件相关的敏感信息，不能放在git里哦，里面就一行代码
```dart
const yamlUrl = "https://xxxx.xx.xxx/config.yaml";
```
